import { create } from "zustand";
import { AgentMessage } from "@/types/os";
import { useFSStore } from "./fsStore";
import { useWindowStore } from "./windowStore";

interface AgentState {
  messages: AgentMessage[];
  isThinking: boolean;
  status: "idle" | "running_task" | "waiting";

  // Actions
  sendMessage: (content: string) => Promise<void>;
  clearHistory: () => void;
}

const INITIAL_MESSAGES: AgentMessage[] = [
  {
    id: "msg-1",
    sender: "agent",
    content: `⚡ Hello! I am your **Omarchy Agent**. I have full direct access to this Web OS:
- I can create and edit files in your virtual filesystem (\`/home/user\`)
- I can run shell commands and build projects
- I can open windows and switch workspaces for you

What would you like to build or inspect today?`,
    timestamp: Date.now() - 30000,
  },
];

export const useAgentStore = create<AgentState>((set, get) => ({
  messages: INITIAL_MESSAGES,
  isThinking: false,
  status: "idle",

  sendMessage: async (userContent: string) => {
    const userMsg: AgentMessage = {
      id: `msg-${Date.now()}`,
      sender: "user",
      content: userContent,
      timestamp: Date.now(),
    };

    set((state) => ({
      messages: [...state.messages, userMsg],
      isThinking: true,
      status: "running_task",
    }));

    // Realistic agent execution simulation with tool calling
    await new Promise((res) => setTimeout(res, 800));

    const lower = userContent.toLowerCase();
    let responseText = "";
    let toolCallInfo: AgentMessage["toolCall"] = undefined;

    if (lower.includes("create") || lower.includes("file") || lower.includes("code")) {
      const fs = useFSStore.getState();
      const filename = "agent_generated_script.js";
      const code = `// Automatically generated by Omarchy Agent
console.log("⚡ Autonomous workflow running on Omarchy Web OS!");
export const systemStatus = {
  os: "Omarchy 4.0 Quattro",
  runtime: "Next.js + WebAssembly",
  tiling: "Hyprland BSP",
  timestamp: new Date().toISOString()
};
`;
      fs.writeFile(`/home/user/projects/${filename}`, code);
      toolCallInfo = {
        name: "fs.writeFile",
        args: { path: `/home/user/projects/${filename}`, size: code.length },
        result: `Successfully wrote ${code.length} bytes to /home/user/projects/${filename}`,
      };
      responseText = `I created \`/home/user/projects/${filename}\` with a sample autonomous agent module! You can open it in Neovim (\`Super+E\`) or inspect it in the terminal with \`cat projects/${filename}\`.`;
    } else if (lower.includes("terminal") || lower.includes("open terminal")) {
      useWindowStore.getState().openWindow("terminal");
      toolCallInfo = {
        name: "wm.openWindow",
        args: { appId: "terminal" },
        result: "Window created",
      };
      responseText = "I've launched a new terminal window for you in the active workspace.";
    } else if (lower.includes("editor") || lower.includes("neovim")) {
      useWindowStore.getState().openWindow("editor");
      toolCallInfo = {
        name: "wm.openWindow",
        args: { appId: "editor" },
        result: "Window created",
      };
      responseText = "I've opened the Neovim code editor.";
    } else if (lower.includes("v86") || lower.includes("kernel") || lower.includes("linux")) {
      useWindowStore.getState().openWindow("v86");
      toolCallInfo = {
        name: "wm.openWindow",
        args: { appId: "v86" },
        result: "v86 VM window opened",
      };
      responseText = "I've launched the real 32-bit x86 Alpine Linux VM running in WebAssembly! You can now run genuine Linux binaries.";
    } else {
      responseText = `Understood. I am monitoring your Omarchy desktop environment. All keyboard commands (\`Super+Enter\`, \`Super+Space\`, \`Super+Q\`, \`Super+1..5\`) and virtual file operations are active. Let me know if you need code generated, scripts executed, or a real x86 Linux kernel booted!`;
    }

    const agentMsg: AgentMessage = {
      id: `msg-${Date.now() + 1}`,
      sender: "agent",
      content: responseText,
      timestamp: Date.now(),
      toolCall: toolCallInfo,
    };

    set((state) => ({
      messages: [...state.messages, agentMsg],
      isThinking: false,
      status: "idle",
    }));
  },

  clearHistory: () => set({ messages: INITIAL_MESSAGES }),
}));
